### PR TITLE
CDM-92: Fix NPE issue with target counter tables with null fields

### LINKED ISSUE #189: CDM 4.1.3 fails with NPE when a target counter table column has null values
Create an Origin  counter table 
```
CREATE TABLE IF NOT EXISTS test_ks.comments_count (
	comment_id text PRIMARY KEY,
	like_count counter, 
	reply_count counter,
	report_count counter,
	seq_counter counter);
```

Create a Target counter table 
```
CREATE TABLE IF NOT EXISTS test_ks.comments_count_dest (
	comment_id text PRIMARY KEY,
	like_count counter, 
	reply_count counter,
	report_count counter,
	seq_counter counter);
```

Add a record to Origin table with no nulls & also add the same record on Target with null in some column
```
token@cqlsh:test_ks> update comments_count set like_count = like_count +1, reply_count = reply_count +1, report_count = report_count + 1, seq_counter = seq_counter +1 where comment_id = 't1';
token@cqlsh:test_ks> update comments_count_dest  set like_count = like_count +1, reply_count = reply_count +1,  seq_counter = seq_counter +1 where comment_id = 't1';token@cqlsh:test_ks> select * FROM comments_count;

 comment_id | like_count | reply_count | report_count | seq_counter
------------+------------+-------------+--------------+-------------
         t1 |          1 |           1 |            1 |           1

token@cqlsh:test_ks> select * FROM comments_count_dest ;

 comment_id | like_count | reply_count | report_count | seq_counter
------------+------------+-------------+--------------+-------------
         t1 |          1 |           1 |         null |           1
```

Now run CDM using version 4.1.3 or earlier 4.x version, you will get the below exception
```

23/08/16 11:39:49 INFO TaskSetManager: Finished task 49.0 in stage 0.0 (TID 49) in 29 ms on pbhat-rmbp16.lan (executor driver) (49/50)
23/08/16 11:39:49 ERROR TargetUpdateStatement: Error trying to bind value:0 to column:report_count of targetDataType:COUNTER/java.lang.Long at column index:3
23/08/16 11:39:49 ERROR CopyJobSession: Error occurred during Attempt#: 1
java.lang.NullPointerException
	at com.datastax.cdm.cql.statement.TargetUpdateStatement.bind(TargetUpdateStatement.java:51)
	at com.datastax.cdm.cql.statement.TargetUpsertStatement.bindRecord(TargetUpsertStatement.java:74)
	at com.datastax.cdm.job.CopyJobSession.bind(CopyJobSession.java:175)
	at com.datastax.cdm.job.CopyJobSession.getDataAndInsert(CopyJobSession.java:98)
	at com.datastax.cdm.job.CopyJobSession.processSlice(CopyJobSession.java:52)
	at com.datastax.cdm.job.CopyJobSession.processSlice(CopyJobSession.java:22)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$3(Migrate.scala:13)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$3$adapted(Migrate.scala:11)
	at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:104)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:121)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:103)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$2(Migrate.scala:11)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$2$adapted(Migrate.scala:10)
	at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:104)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:121)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:103)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$1(Migrate.scala:10)
	at com.datastax.cdm.job.Migrate$.$anonfun$execute$1$adapted(Migrate.scala:9)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at org.apache.spark.InterruptibleIterator.foreach(InterruptibleIterator.scala:28)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2(RDD.scala:1003)
	at org.apache.spark.rdd.RDD.$anonfun$foreach$2$adapted(RDD.scala:1003)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
23/08/16 11:39:49 ERROR CopyJobSession: Error with PartitionRange -- ThreadID: 94 Processing min: 4058283696216101360 max: 4242751136953196876 -- Attempt# 1
23/08/16 11:39:49 ERROR CopyJobSession: Error stats Read#: 1, Wrote#: 0, Skipped#: 0, Error#: 1
```

### PR DESCRIPTION
**Pull request by pravinbhat**
**What this PR does**: Fixes NPE issue when there are null values in target counter tables.

**Which issue(s) this PR fixes**:
Fixes #189 

**Checklist:**
- [x] Automated Tests added/updated
- [x] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by msmygit — APPROVED** [review]

File: src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java [hunk 1]
```diff
@@ -42,35 +42,39 @@ protected BoundStatement bind(Row originRow, Row targetRow, Integer ttl, Long wr
             boundStatement = boundStatement.set(currentBindIndex++, writeTime, Long.class);
         }
 
-        Object bindValue = null;
+        Object bindValueOrg = null;
```
Comment (msmygit) [inline src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java:45]: #nitpick on the variable names used. We use `origin` / `destination` here and `source` / `target` else.

File: RELEASE.md [hunk 2]
```diff
@@ -1,5 +1,8 @@
 # Release Notes
-## [4.1.3] - 2023-07-06
+## [4.1.4] - 2023-08-16
+- In rare edge situations, counter tables with existing data in Target can have null values on target. This release will handle null values in Target counter table transparently.
```
[the remark this answers is not in the document]
Comment (pravinbhat) [reply RELEASE.md:3]: @mieslep Yes, null values are possible on both origin & target. This & the previous PR handles the same

File: src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java [hunk 3]
```diff
@@ -42,35 +42,39 @@ protected BoundStatement bind(Row originRow, Row targetRow, Integer ttl, Long wr
...
-                    if (null == bindValue) {
+                if (usingCounter && counterIndexes.contains(targetIndex)) {
+                    bindValueOrigin = cqlTable.getOtherCqlTable().getData(originIndex, originRow);
+                    if (null == bindValueOrigin) {
                         currentBindIndex++;
                         continue;
                     }
-                    bindValue = ((Long) bindValue - (null==targetRow ? 0 : (Long) cqlTable.getData(targetIndex, targetRow)));
+                    bindValueTarget = (null == targetRow ? 0L : cqlTable.getData(targetIndex, targetRow));
+                    bindValueTarget = ((Long) bindValueOrigin - (null == bindValueTarget ? 0L : (Long) bindValueTarget));
```
Comment (mieslep) [inline src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java:58]: I don't understand this fully - we've done null protection so why not just reset to bindValueOrigin - bindValueTarget?  And what if origin value is null? Discussion may clear this up...

**Review by mieslep — CHANGES_REQUESTED** [review]

File: SIT/smoke/04_counters/setup.cql [hunk 4]
```diff
@@ -11,4 +11,6 @@ UPDATE origin.smoke_counters set col1=col1+500 where key='record6';
 DROP TABLE IF EXISTS target.smoke_counters;
 CREATE TABLE target.smoke_counters(key text,col1 counter,col2 counter, PRIMARY KEY (key));
 
+UPDATE target.smoke_counters set col1=col1+1 where key='record1';
```
[the remark this answers is not in the document]
Comment (pravinbhat) [reply SIT/smoke/04_counters/setup.cql:14]: @mieslep This is a counter table & updates are inserts. Note that this will add a new record to target with null values in col2.

File: src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java (hunk 3 above)
Comment (mieslep) [reply src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java:58]: Ah I think I see it now, some code comments would be good...
First one is "what is the value on target, if the whole targetRow does not exist use a value of 0". Second one is "compute if the value itself on a non-null targetRow is null".

Comment (pravinbhat) [reply src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java:58]: Agree this is a bit confusing, but most of the confusion is due to how counter tables work in Cassandra & how nulls work in Java. I find looking at actual code to be the best docs in such scenarios.

Comment (mieslep) [reply src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java:58]: Yes but in this case the code confused me as we set `bindValueTarget` twice :)  First entry could be maybe `long bindValueTargetFromRow`  if we wanted to use code as documentation?

Comment (pravinbhat) [reply src/main/java/com/datastax/cdm/cql/statement/TargetUpdateStatement.java]: The first is handling if the entire row is null & the second is handling if the column value is null. But in both scenarios the variable is storing the target column values (not row). I have updated the variable naming for the whole section to be more clear.
