### PR TITLE
fix: Double quoting keyspace name to allow for mixed cased characters

### LINKED ISSUE #400: Track didn't work when "KeyspaceName" has uppercase.
The error says:
```
Exception in thread "main" com.datastax.oss.driver.api.core.servererrors.InvalidConfigurationInQueryException: Keyspace keyspacename doesn't exist

Caused by:
        this.session.execute("CREATE TABLE IF NOT EXISTS " + cdmKsTabInfo
                + " (table_name TEXT, run_id BIGINT, run_type TEXT, prev_run_id BIGINT, start_time TIMESTAMP, end_time TIMESTAMP, run_info TEXT, status TEXT, PRIMARY KEY (table_name, run_id))");
```

Stack trace error:
```
25/11/12 13:29:22 INFO CassandraConnector: Connected to Cassandra cluster.
Exception in thread "main" com.datastax.oss.driver.api.core.servererrors.InvalidConfigurationInQueryException: Keyspace keyspacename doesn't exist
	at com.datastax.oss.driver.api.core.servererrors.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:54)
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:154)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:55)
	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:32)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:234)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:56)
	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.datastax.spark.connector.cql.SessionProxy.invoke(SessionProxy.scala:43)
	at com.sun.proxy.$Proxy59.execute(Unknown Source)
	at com.datastax.cdm.cql.statement.TargetUpsertRunDetailsStatement.<init>(TargetUpsertRunDetailsStatement.java:63)
	at com.datastax.cdm.feature.TrackRun.<init>(TrackRun.java:39)
	at com.datastax.cdm.job.BasePartitionJob.$anonfun$getParts$4(BasePartitionJob.scala:38)
	at com.datastax.spark.connector.cql.CassandraConnector.$anonfun$withSessionDo$1(CassandraConnector.scala:104)
	at com.datastax.spark.connector.cql.CassandraConnector.closeResourceAfterUse(CassandraConnector.scala:121)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:103)
	at com.datastax.cdm.job.BasePartitionJob.getParts(BasePartitionJob.scala:38)
	at com.datastax.cdm.job.BaseJob.setup(BaseJob.scala:102)
	at com.datastax.cdm.job.Migrate$.delayedEndpoint$com$datastax$cdm$job$Migrate$1(Migrate.scala:26)
	at com.datastax.cdm.job.Migrate$delayedInit$body.apply(Migrate.scala:24)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.datastax.cdm.job.BaseJob.main(BaseJob.scala:34)
	at com.datastax.cdm.job.Migrate.main(Migrate.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1034)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:199)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:222)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
25/11/12 13:29:22 INFO SparkContext: Invoking stop() from shutdown hook
```

### PR DESCRIPTION
**Pull request by abonacin**
**What this PR does**: Bugfix to allow KeyspaceName with upper case on the target cluster.

**Which issue(s) this PR fixes**: 
Fixes #400

**Checklist:**
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public TargetUpsertRunDetailsStatement(CqlSession session, String keyspaceTable)
         if (ksTab.length != 2) {
             throw new RuntimeException("Invalid keyspace.table format: " + keyspaceTable);
         }
-        this.keyspaceName = ksTab[0];
+        this.keyspaceName = "\"" + ksTab[0] + "\"";
         this.tableName = ksTab[1];
```
Comment (msmygit) [inline src/main/java/com/datastax/cdm/cql/statement/TargetUpsertRunDetailsStatement.java]: Should we also perform the same treatment for the table name too?

**Review by msmygit — APPROVED** [review]
LGTM 👍🏼
