### PR TITLE
Fix OOM issue # 242

### LINKED ISSUE #242: java.lang.OutOfMemoryError: Java heap space when running validation CDM job with 4.1.11
### How to reproduce?

- NoSQLBench workload yaml file is as follows:

<details>
  <summary>Click here to expand/collapse</summary>
  
  ```
  description: Auto-generated workload from source schema.
  scenarios:
    default:
      schema: run driver=cql tags=block:"schema.*" threads===UNDEF cycles===UNDEF
      rampup: run driver=cql tags=block:"rampup.*" threads=auto cycles===TEMPLATE(rampup-cycles,10000)
      main: run driver=cql tags=block:"main.*" threads=auto cycles===TEMPLATE(main-cycles,10000)
    main_insert: run driver=cql tags=block:main-insert threads=auto cycles===TEMPLATE(main-cycles,10000)
    main_select: run driver=cql tags=block:main-select threads=auto cycles===TEMPLATE(main-cycles,10000)
    main-scan: run driver=cql tags=block:main-scan threads=auto cycles===TEMPLATE(main-cycles,10000)
    main-update: run driver=cql tags=block:main-update threads=auto cycles===TEMPLATE(main-cycles,10000)
    truncate: run driver=cql tags=block:'truncate.*' threads===UNDEF cycles===UNDEF
    schema-keyspaces: run driver=cql tags=block:schema-keyspaces threads===UNDEF cycles===UNDEF
    schema-types: run driver=cql tags=block:schema-types threads===UNDEF cycles===UNDEF
    schema-tables: run driver=cql tags=block:schema-tables threads===UNDEF cycles===UNDEF
    drop: run driver=cql tags=block:'drop.*' threads===UNDEF cycles===UNDEF
    drop_tables: run driver=cql tags=block:drop-tables threads===UNDEF cycles===UNDEF
    drop-types: run driver=cql tags=block:drop-types threads===UNDEF cycles===UNDEF
    drop-keyspaces: run driver=cql tags=block:drop-keyspaces threads===UNDEF cycles===UNDEF
  bindings:
    text: NumberNameToString();
    bigint: Identity();
    blob: ByteBufferSizedHashed(30);
    boolean: ToBoolean();
    date: EpochMillisToJavaLocalDate();
    decimal: ToBigDecimal();
    double: HashRange(0.0,1.0);
    duration: ToCqlDurationNanos();
    float: HashRange(0.0,1.0); DoubleToFloat();
    frozen<list<int>>: ListSizedHashed(HashRange(3,7),ToInt()));
    list<text>: ListStepped(NumberNameToString(),NumberNameToString())
    map<text,text>: MapSized(3, Combinations('A-Z;0-9'), NumberNameToString(), ToString());
    set<text>: SetSized(HashRange(3,4),NumberNameToString()));
    smallint: ToShort();
    time: StartingEpochMillis('2022-01-01 00:00:00'); ToLocalTime();
    timestamp: ToJavaInstant();
    timeuuid: ToEpochTimeUUID();
    tinyint: ToByte();
    uuid: ToUUID();
    varint: ToBigInt();
    ascii: NumberNameToString();
    inet: ToInetAddress();
    int: ToInt();
    #frozen<list<float>>: ListSizedHashed(HashRange(1,1000),HashRange(0.0,1.0); DoubleToFloat();)
    #frozen<list<float>>: ListSizedHashed(HashRange(1,1000),ListHashed(HashRange(0.0,1.0),DoubleToFloat()))
    frozen<list<float>>: ListSizedHashed(HashRange(1,1000)->int,HashRange(0.0f,9999999.0f)))
  blocks:
    schema-keyspaces:
      params:
        timeout: 60.0
      ops:
        create-keyspace-TEMPLATE(keyspace,ks_00001):
          simple: |
            create keyspace IF NOT EXISTS TEMPLATE(keyspace,ks_00001) with replication = {'class': 'SimpleStrategy','replication_factor': 'TEMPLATE(rf,1)'};
    schema-tables:
      params:
        timeout: 60.0
      ops:
        create-tb_00001-table-tb_00001:
          simple: |
            create table if not exists TEMPLATE(keyspace,ks_00001).tb_00001 (
            col_00001 text,
            col_00002 bigint,
            col_00003 blob,
            col_00004 boolean,
            col_00005 date,
            col_00006 decimal,
            col_00007 double,
            col_00008 duration,
            col_00009 float,
            col_00010 frozen<list<int>>,
            col_00011 list<text>,
            col_00012 map<text,text>,
            col_00013 set<text>,
            col_00014 smallint,
            col_00015 text,
            col_00016 time,
            col_00017 timestamp,
            col_00018 timeuuid,
            col_00019 tinyint,
            col_00020 uuid,
            col_00021 text,
            col_00022 varint,
            col_00023 ascii,
            col_00024 inet,
            col_00025 int,
            col_00026 frozen<list<float>>,
            primary key ((col_00001))
            );
    schema-types:
      params: {
        }
      ops: {
        }
    truncate_tables:
      params:
        timeout: 900.0
      ops:
        truncate-tb_00001-table-tb_00001:
          simple: truncate TEMPLATE(keyspace,ks_00001).tb_00001;
    drop-types:
      params: {
        }
      ops: {
        }
    drop_tables:
      params:
        timeout: 900.0
      ops:
        drop-tb_00001-table-tb_00001:
          simple: drop table if exists TEMPLATE(keyspace,ks_00001).tb_00001;
    drop-keyspaces:
      params: {
        }
      ops: {
        }
    rampup:
      params:
        timeout: 10.0
      ops:
        insert-tb_00001-table-tb_00001:
          prepared: |
            insert into TEMPLATE(keyspace,ks_00001).tb_00001
            ( col_00001, col_00002, col_00003, col_00004, col_00005, col_00006, col_00007, col_00008, col_00009, col_00010, col_00011, col_00012, col_00013, col_00014, col_00015, col_00016, col_00017, col_00018, col_00019, col_00020, col_00021, col_00022, col_00023, col_00024, col_00025, col_00026)
            VALUES
            ( {text}, {bigint}, {blob}, {boolean}, {date}, {decimal}, {double}, {duration}, {float}, {frozen<list<int>>}, {list<text>}, {map<text,text>}, {set<text>}, {smallint}, {text}, {time}, {timestamp}, {timeuuid}, {tinyint}, {uuid}, {text}, {varint}, {ascii}, {inet}, {int}, {frozen<list<float>>} );
          ratio: 1
    main_insert:
      params:
        timeout: 10.0
      ops:
        insert-tb_00001-table-tb_00001:
          prepared: |
            insert into TEMPLATE(keyspace,ks_00001).tb_00001
            ( col_00001, col_00002, col_00003, col_00004, col_00005, col_00006, col_00007, col_00008, col_00009, col_00010, col_00011, col_00012, col_00013, col_00014, col_00015, col_00016, col_00017, col_00018, col_00019, col_00020, col_00021, col_00022, col_00023, col_00024, col_00025, col_00026)
            VALUES
            ( {text}, {bigint}, {blob}, {boolean}, {date}, {decimal}, {double}, {duration}, {float}, {frozen<list<int>>}, {list<text>}, {map<text,text>}, {set<text>}, {smallint}, {text}, {time}, {timestamp}, {timeuuid}, {tinyint}, {uuid}, {text}, {varint}, {ascii}, {inet}, {int}, {frozen<list<float>>} );
          ratio: 1
    main_select:
      params:
        timeout: 10.0
      ops:
        select-tb_00001-table-tb_00001:
          prepared: |
            select * from  TEMPLATE(keyspace,ks_00001).tb_00001
            where col_00001={text}
            LIMIT 10;
          ratio: 1
    main-scan:
      params:
        timeout: 30.0
      ops:
        scan-tb_00001-table-tb_00001:
          prepared: "select * from TEMPLATE(keyspace,ks_00001).tb_00001 LIMIT 10;"
          ratio: 1
    main-update:
      params:
        timeout: 10.0
      ops:
        update-tb_00001-table-tb_00001:
          prepared: |
            update TEMPLATE(keyspace,ks_00001).tb_00001
            set col_00002={bigint}, col_00003={blob}, col_00004={boolean}, col_00005={date}, col_00006={decimal}, col_00007={double}, col_00008={duration}, col_00009={float}, col_00010={frozen<list<int>>}, col_00011={list<text>}, col_00012={map<text,text>}, col_00013={set<text>}, col_00014={smallint}, col_00015={text}, col_00016={time}, col_00017={timestamp}, col_00018={timeuuid}, col_00019={tinyint}, col_00020={uuid}, col_00021={text}, col_00022={varint}, col_00023={ascii}, col_00024={inet}, col_00025={int}, col_00026={frozen<list<float>>}
            where col_00001={text};
          ratio: 1
  params:
    cl: LOCAL_QUORUM
  ```
</details>

- Get latest `5.17.x` version of NoSQLBench
   ```
   wget https://github.com/nosqlbench/nosqlbench/releases/download/5.17.9-release/nb5 && chmod +x nb5
   ```
- Execute the following invocation command
   ```
   ./nb5 ./cql_alltypes.yaml default hosts=dse0 localdc=dc1 username=cassandra password=cassandra keyspace=baselines rampup-cycles=10000000 main-cycles=300000000 stride=60 striderate=1000 errors=counter,warn -v --progress console:1m --show-stacktraces
   ```

### CDM Details
- Version `4.1.11`
- Properties file - nothing fancy in it. `numParts` is set to `10000`
- Command:
```
ubuntu@ip-1:~/assets$ ./spark-3.4.1-bin-hadoop3-scala2.13/bin/spark-submit --properties-file cdm.properties --master "local[*]" --driver-memory 6G --executor-memory 16G --class com.datastax.cdm.job.DiffData cassandra-data-migrator-4.1.11.jar &> logfile_name_$(date +%Y%m%d_%H_%M).txt
```
### Stacktrace
```
24/01/23 02:01:32 INFO SplitPartitions: ThreadID: 1 Splitting partitions in file: ./baselines.tb_00001_partitions.csv using a split-size of 10000
Exception in thread "main" Exception in thread "RemoteBlock-temp-file-clean-thread" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.ArrayList.grow(ArrayList.java:238)
        at java.base/java.util.ArrayList.grow(ArrayList.java:243)
        at java.base/java.util.ArrayList.add(ArrayList.java:486)
        at java.base/java.util.ArrayList.add(ArrayList.java:499)
        at com.datastax.cdm.job.SplitPartitions.getSubPartitions(SplitPartitions.java:110)
        at com.datastax.cdm.job.SplitPartitions.getSubPartitionsFromFile(SplitPartitions.java:45)
        at com.datastax.cdm.job.BasePartitionJob.getParts(BasePartitionJob.scala:11)
        at com.datastax.cdm.job.BaseJob.setup(BaseJob.scala:74)
        at com.datastax.cdm.job.DiffData$.delayedEndpoint$com$datastax$cdm$job$DiffData$1(DiffData.scala:4)
        at com.datastax.cdm.job.DiffData$delayedInit$body.apply(DiffData.scala:3)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1(App.scala:76)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.App$$Lambda$342/0x000000084031f840.apply(Unknown Source)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at com.datastax.cdm.job.BaseJob.main(BaseJob.scala:18)
        at com.datastax.cdm.job.DiffData.main(DiffData.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1020)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
java.lang.OutOfMemoryError: Java heap space
```

### PR DESCRIPTION
**Pull request by pravinbhat**
**What this PR does**:
Fixes OOM exception when partition file present and numParts has a high value

**Which issue(s) this PR fixes**:
Fixes #242 

**Checklist:**
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Review by msmygit — APPROVED** [review]

**Review by faizalrub-datastax — APPROVED** [review]
Praveen, I see that the MAX_NUM_PARTS_FOR_PARTITION_FILE = 10. Does this mean always the numParts will be 10 when reading partition ranges from CSV file?  There could be partition ranges that require more than 10 for large datasets.

**Comment by pravinbhat** [comment]
> Praveen, I see that the MAX_NUM_PARTS_FOR_PARTITION_FILE = 10. Does this mean always the numParts will be 10 when reading partition ranges from CSV file? There could be partition ranges that require more than 10 for large datasets.

Good question @faizalrub-datastax. No, the num-parts value further splits each partition that is listed in the partition csv file. i.e. If the partition file has 100 partitions min/max lines & num-parts is set to 10, that will effectively convert to 100 * 10 = 1000 partitions. What was happening now is, when we run a default job with 10K numparts & then there are a few failures, let say 100. If you rerun this job, it will retry those 100 failed partition by split each of those partition by 10K, so effectively 100 * 10K = 1M partitions, which causes the OOM. Note that MAX_NUM_PARTS_FOR_PARTITION_FILE prop is used only when using a partition-file with the partitions listed. Ideally in such scenarios, the num-part should be set to 1 unless the failure was caused due to a large partition-range. If it is a large partition-range the max we may need to further split will not be more than 10. Hope this clarifies.

File: src/main/java/com/datastax/cdm/job/SplitPartitions.java [hunk 1]
```diff
@@ -24,16 +24,17 @@
...
 import java.util.List;
+import java.util.regex.Pattern;
 import java.util.stream.Collectors;
 import java.util.stream.IntStream;
 import java.util.stream.Stream;
 
 public class SplitPartitions {
 
     public static Logger logger = LoggerFactory.getLogger(SplitPartitions.class.getName());
+    private static final int MAX_NUM_PARTS_FOR_PARTITION_FILE = 10;
```
Comment (msmygit) [inline src/main/java/com/datastax/cdm/job/SplitPartitions.java:37]: Sorry just a thought popped up now. Should we keep this setting with an unexposed configurable variable so we don't have to change the code in case we need to try out higher `numParts` in future?
