### PR TITLE
Fix auto column mapping bug when target has more columns than origin

### LINKED ISSUE #374: migrate job fails when target table has more columns than source table
At a customer environment, we noticed that when the target table schema had additional columns compared to the source, we would see errors like the following:

```
25/06/17 10:21:10 ERROR CopyJobSession: Error with PartitionRange -- ThreadID: 115 Processing min: -6271892985061247544 max: -5902958103587056512
java.util.concurrent.CompletionException: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Invalid unset value for column email_typ_cde
...
```

If we could auto-account for the mismatched col count, and leave the rest unset, it would allow for success in these scenarios.

### PR DESCRIPTION
**Pull request by pravinbhat**
**What this PR does**: Fixes auto column mapping bug when target has more columns than origin

**Which issue(s) this PR fixes**:
Fixes #374 

**Checklist:**
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/main/java/com/datastax/cdm/job/DiffJobSession.java [hunk 1]
```diff
@@ -290,12 +290,6 @@ private String isDifferent(Record record) {
                                         pk, targetIndex, targetColumnNames.get(targetIndex), origin);
                         } else if (targetIndex == extractJsonFeature.getTargetColumnIndex()) {
                             originIndex = extractJsonFeature.getOriginColumnIndex();
-                        } else {
```
Comment (msmygit) [inline src/main/java/com/datastax/cdm/job/DiffJobSession.java:293]: Instead, can we log a warning here?

**Review by msmygit — APPROVED** [review]
